using System.Threading.Tasks;
using C485.DataverseClientProxy.Models;

namespace C485.DataverseClientProxy.Interfaces;

public interface IDataverseClientProxy : IDataverseConnectionLayer
{
	AdvancedExecuteMultipleRequestsStatistics AdvancedExecuteMultipleRequests(
		ExecuteMultipleRequestBuilder executeMultipleRequestBuilder,
		ExecuteMultipleRequestSettings executeMultipleRequestSettings);

	Task<AdvancedExecuteMultipleRequestsStatistics> AdvancedExecuteMultipleRequestsAsync(
		ExecuteMultipleRequestBuilder executeMultipleRequestBuilder,
		ExecuteMultipleRequestSettings executeMultipleRequestSettings);
}